### ISSUE TITLE
Rework OAuth Database

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#110]
https://github.com/FAForever/faf-java-api/issues/68

- [ ] `oauth_tokens.client_id` has no `foreign key` to `oauth_clients.id`
- [ ] Is `oauth_clients.client_type` needed? replace by enum?
- [ ] How to implement `scopes`? Do we really want to store them in one column?
- [ ] Is `icon_url` needed?
- [ ] Is `auto_approve_scopes` needed?

**Comment by IDragonfire** [comment]
Note: not every column is needed in every authentication flow

**Comment by IDragonfire** [comment]
But why not an enum for `client_type` with `confidential` and `public`

**Comment by micheljung** [comment]
I never said "no" to making it an enum. However, since you ask, there are other people who raise [some good points against the usage of enum](http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/). Btw, the API [already uses a (Java) enum ](https://github.com/FAForever/faf-java-api/blob/40c4caf0e9ecc60b71192428de3144b5f605fc17/src/main/java/com/faforever/api/client/OAuthClient.java#L23-L23).

**Comment by IDragonfire** [comment]
good article, maybe we should use a `TINYINT(1)`

**Comment by micheljung** [comment]
Fun fact, the `(1)` only defines with how many leading zeroes a value should be printed with when using `zerofill` - not the number of digits that can be stored :)

But yes, either a tinyint (that could be the foreign key of a table that contains scopes, but that seems overengineered), or just varchar. I wouldn't like values like 1, 2 where one has to look up the meaning in a table column first, and once it's adjusted nobody updates the comment etc. Sometimes it's easier if there are just string values everyone can read and understand.

**Comment by Brutus5000** [comment]
Sounds obselete and referenced issue is closed.
