### ISSUE TITLE
table `lobby_ban` doesn't accept revoked bans

### ISSUE THREAD

**Issue by norraxx** [FAForever/db#209]
`lobby_ban` table doesn't count with ban revokes.
It could be fixed by adding one more condition in where `AND revoke IS NULL`.

**Comment by Askaholic** [comment]
Revoked bans work fine, I know because I have a unit test for it on the server. See 
https://github.com/FAForever/server/blob/aee9965f7eaebbbe9ab273444bc8a6eaa105f81c/tests/integration_tests/test_server.py#L69
and
https://github.com/FAForever/server/blob/aee9965f7eaebbbe9ab273444bc8a6eaa105f81c/tests/data/test-data.sql#L46

In case of a revoked ban the `lobby_ban` view's `expires_at` time will be the revoke time. Meaning that revoking a ban is the same as changing it's expiry time.
