### ISSUE TITLE
Remove CURRENT_TIMESTAMP for game_stats.startTime

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#83]
`game_stats.startTime` is currently set implicitly by `DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` which, if you think about it for one second, is not a smart thing to do.

This causes any game that have any of its values updated (like `validity`) when the game ends to have its `startTime` set to the game end time. Outch!

**Comment by duk3luk3** [comment]
Can't this one be fixed simply by removing the `ON UPDATE CURRENT_TIMESTAMP`?

**Comment by micheljung** [comment]
Yes, that's sufficient.

**Comment by duk3luk3** [comment]
Can we close https://github.com/FAForever/server/issues/288 then?

**Comment by micheljung** [comment]
I'm not sure. It's rather a "coincidence" that the `startTime` of a game and the insertion time into the database are the same, rather than a technical implication. In future, the server could as well store the game before it's started.

Which also makes me doubt whether we really should have  `DEFAULT CURRENT_TIMESTAMP`.
Your opinions, @duk3luk @Brutus5000 @IDragonfire 3 ?

**Comment by duk3luk3** [comment]
You're right. But I'd like to not make any unneeded changes to the lobbyserver because we don't really have a proper maintainer for it.

So there's a simple, risk-free way to fix the bug, which is just using ` DEFAULT CURRENT_TIMESTAMP` without `ON UPDATE`. Changing server code is a lot more risky and will not have an immediate benefit.

It's not an elegant solution, but it's the most robust solution for now.

**Comment by micheljung** [comment]
Ok, let's keep it for now.
